#!/usr/bin/env python3
"""
build_map.py
------------
Turn a plain list of YouTube links into a new map page.

You paste a bunch of video links into a text file (one per line — from any
channel, in any common URL format). This script:

    1. pulls the video id out of each link,
    2. looks up each video's title (used as the marker name),
    3. writes a new  <slug>.html  and  <slug>.js  for the map,
    4. adds a card for it to index.html.

Coordinates are left as null — fill in lat/lng by hand in the generated .js
(right-click a spot in Google Maps to copy its coordinates).

--------------------------------------------------------------------------
SETUP
--------------------------------------------------------------------------
    pip install requests        # only needed for automatic title lookup

--------------------------------------------------------------------------
USAGE
--------------------------------------------------------------------------
    python build_map.py links.txt --out my-map --title "My Map"

    links.txt   a text file with one YouTube link per line. Blank lines and
                lines starting with # are ignored. These all work:
                    https://www.youtube.com/watch?v=CzTVxom0asE
                    https://youtu.be/CzTVxom0asE
                    https://www.youtube.com/shorts/CzTVxom0asE
                    CzTVxom0asE

    --out       filename slug for the new page (creates <slug>.html + <slug>.js)
    --title     the heading shown on the map (default: derived from --out)

Options:
    --no-titles   skip the online title lookup; use "Video <id>" placeholders
    --no-index    don't touch index.html
    --note TEXT   description shown on the index.html card

Example:
    python build_map.py my-links.txt --out tokyo-eats --title "Tokyo Eats" --note "Spots I want to try"
--------------------------------------------------------------------------
"""

import re
import sys
import os
import json
import argparse
from urllib.parse import urlparse, parse_qs, unquote

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

try:
    import requests
except ImportError:
    requests = None


ID = r"[A-Za-z0-9_-]{11}"
ID_PATTERNS = [
    re.compile(r"[?&]v=(" + ID + r")"),
    re.compile(r"youtu\.be/(" + ID + r")"),
    re.compile(r"/shorts/(" + ID + r")"),
    re.compile(r"/embed/(" + ID + r")"),
    re.compile(r"/live/(" + ID + r")"),
]
BARE_ID = re.compile(r"^(" + ID + r")$")


def ids_from_line(line):
    """Yield every video id found in one line of the links file."""
    line = line.strip()
    if not line or line.startswith("#"):
        return []

    # Unwrap a YouTube redirect link: the real target is in the q= parameter.
    if "youtube.com/redirect" in line:
        qs = parse_qs(urlparse(line).query)
        if "v" in qs:
            return [qs["v"][0]]
        if "q" in qs:
            line = unquote(qs["q"][0])

    found = []
    for pat in ID_PATTERNS:
        for m in pat.finditer(line):
            found.append(m.group(1))
    m = BARE_ID.match(line)
    if m:
        found.append(m.group(1))
    return found


def read_ids(path):
    """Read the links file and return an ordered, de-duplicated list of ids."""
    seen = set()
    ids = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            for vid in ids_from_line(line):
                if vid not in seen:
                    seen.add(vid)
                    ids.append(vid)
    return ids


def fetch_title(video_id, session):
    """Look up a video's title via YouTube's oEmbed endpoint. Returns None on failure."""
    url = "https://www.youtube.com/oembed?format=json&url=https://www.youtube.com/watch?v=" + video_id
    try:
        r = session.get(url, timeout=15)
        if r.status_code == 200:
            return r.json().get("title")
    except Exception:
        pass
    return None


def get_titles(ids, do_lookup):
    titles = {}
    if do_lookup:
        if requests is None:
            print("(!) requests not installed — using placeholder titles. Run: pip install requests")
            do_lookup = False
    if do_lookup:
        session = requests.Session()
        session.headers.update({"User-Agent": "Mozilla/5.0"})
        for i, vid in enumerate(ids, 1):
            t = fetch_title(vid, session)
            print("  [%d/%d] %s -> %s" % (i, len(ids), vid, t or "(no title found)"))
            titles[vid] = t or ("Video " + vid)
    else:
        for vid in ids:
            titles[vid] = "Video " + vid
    return titles


def write_js(path, map_title, ids, titles):
    safe_title = map_title.replace('"', "'")
    with open(path, "w", encoding="utf-8") as f:
        f.write("// Generated by build_map.py. Loaded by the .html page before map.js.\n")
        f.write("// Fill in lat/lng for each video (right-click a spot in Google Maps to copy coords).\n")
        f.write("// Entries with lat/lng null won't appear until you add coordinates.\n\n")
        f.write('const MAP_TITLE = "%s";\n\n' % safe_title)
        f.write("const PLACES = [\n")
        for vid in ids:
            t = titles.get(vid, "Video " + vid).replace('"', "'")
            f.write('  { title: "%s", video: "%s", lat: null, lng: null },\n'
                    % (t, "https://www.youtube.com/watch?v=" + vid))
        f.write("];\n")


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>%(title)s &mdash; Map</title>

<!-- Leaflet -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.css" />
<!-- Shared styles -->
<link rel="stylesheet" href="style.css" />
</head>
<body>
  <div class="titlebar" id="titlebar"></div>
  <div id="map"></div>

  <!-- 1) Leaflet  2) this map's data  3) the shared renderer -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.js"></script>
  <script src="%(datafile)s"></script>
  <script src="map.js"></script>
</body>
</html>
"""


def write_html(path, map_title, datafile):
    with open(path, "w", encoding="utf-8") as f:
        f.write(HTML_TEMPLATE % {"title": map_title, "datafile": datafile})


def add_to_index(index_path, html_file, name, note):
    """Insert a card entry into the CHANNELS list in index.html (best effort)."""
    if not os.path.exists(index_path):
        print("(!) %s not found — skipping index update." % index_path)
        return
    with open(index_path, encoding="utf-8") as f:
        text = f.read()

    if ('file: "%s"' % html_file) in text:
        print("index.html already has an entry for %s — leaving it." % html_file)
        return

    marker = "const CHANNELS = ["
    i = text.find(marker)
    if i == -1:
        print("(!) Couldn't find the CHANNELS list in index.html — add the card manually.")
        return

    insert_at = i + len(marker)
    safe_name = name.replace('"', "'")
    safe_note = (note or "").replace('"', "'")
    entry = '\n  { file: "%s", name: "%s", note: "%s" },' % (html_file, safe_name, safe_note)
    new_text = text[:insert_at] + entry + text[insert_at:]
    with open(index_path, "w", encoding="utf-8") as f:
        f.write(new_text)
    print("Added a card to index.html.")


def main():
    ap = argparse.ArgumentParser(description="Build a map page from a list of YouTube links.")
    ap.add_argument("links", help="Text file with one YouTube link per line")
    ap.add_argument("--out", required=True, help="Filename slug (creates <slug>.html and <slug>.js)")
    ap.add_argument("--title", default=None, help="Map heading (default: derived from --out)")
    ap.add_argument("--note", default="", help="Description shown on the index.html card")
    ap.add_argument("--no-titles", action="store_true", help="Skip online title lookup")
    ap.add_argument("--no-index", action="store_true", help="Don't modify index.html")
    args = ap.parse_args()

    slug = args.out
    map_title = args.title or slug.replace("-", " ").replace("_", " ").title()

    ids = read_ids(args.links)
    if not ids:
        sys.exit("No YouTube video links found in %s." % args.links)
    print("Found %d video link(s)." % len(ids))

    titles = get_titles(ids, do_lookup=not args.no_titles)

    js_name = slug + ".js"
    html_name = slug + ".html"
    write_js(os.path.join(ROOT, js_name), map_title, ids, titles)
    write_html(os.path.join(ROOT, html_name), map_title, js_name)
    print("Wrote %s and %s" % (html_name, js_name))

    if not args.no_index:
        add_to_index(os.path.join(ROOT, "index.html"), html_name, map_title, args.note)

    print("\nNext: open %s and fill in lat/lng for each entry." % js_name)


if __name__ == "__main__":
    main()
