#!/usr/bin/env python3
"""
csv_to_map.py
-------------
Turn a curated CSV of places into a map page (<slug>.html + <slug>.js) and add
a card for it to index.html.

Use this for channels where you build the data as a spreadsheet by hand — for
example the CSV produced by parse_timeteam.py. (For a plain list of video links
with no coordinates, use build_map.py instead.)

Expected CSV columns (extra columns are ignored):
    title       text for the row (used as a fallback marker label)
    video_url   the YouTube link
    location    place name (default marker label)
    lat, lng    coordinates (blank rows are kept with null, so they simply
                don't appear on the map until you fill them in)
    season, episode   optional; appended to the label as "(S7 E7)"

--------------------------------------------------------------------------
USAGE
--------------------------------------------------------------------------
    python csv_to_map.py timeteam-classics.csv --title "Time Team Classics" --note "UK archaeology digs"

The marker's hover label shows up to three lines: title, then location, then
"Sx Ey" (any that are present in the CSV).

Options:
    --out SLUG     output name (default: CSV filename without .csv)
    --title TEXT   map heading / MAP_TITLE (default: derived from --out)
    --note TEXT    description shown on the index.html card
    --no-html      don't (re)write the <slug>.html page
    --no-index     don't modify index.html
--------------------------------------------------------------------------
"""

import os
import csv
import sys
import argparse

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def read_places(path):
    rows = []
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for r in reader:
            location = (r.get("location") or "").strip()
            title = (r.get("title") or "").strip()
            # First label line is the title; fall back to the location if there's
            # no title. Don't repeat the location on its own line if it's the title.
            first = title or location
            rows.append({
                "title": first,
                "location": location if location and location != first else "",
                "season": (r.get("season") or "").strip(),
                "episode": (r.get("episode") or "").strip(),
                "video": (r.get("video_url") or "").strip(),
                "lat": _num(r.get("lat")),
                "lng": _num(r.get("lng")),
            })
    return rows


def _num(v):
    """Return a float string for the .js, or 'null' if blank/unparseable."""
    v = (v or "").strip()
    if not v:
        return "null"
    try:
        float(v)
        return v
    except ValueError:
        return "null"


def write_js(path, map_title, rows):
    safe_title = map_title.replace('"', "'")
    with open(path, "w", encoding="utf-8") as f:
        f.write("// Generated by csv_to_map.py. Loaded by the .html page before map.js.\n")
        f.write("// Entries with lat/lng null won't appear until coordinates are filled in.\n\n")
        f.write('const MAP_TITLE = "%s";\n\n' % safe_title)
        f.write("const PLACES = [\n")
        for r in rows:
            title = r["title"].replace('"', "'")
            location = r["location"].replace('"', "'")
            season = r["season"] if r["season"].isdigit() else "null"
            episode = r["episode"] if r["episode"].isdigit() else "null"
            f.write('  { title: "%s", location: "%s", season: %s, episode: %s, video: "%s", lat: %s, lng: %s },\n'
                    % (title, location, season, episode, r["video"], r["lat"], r["lng"]))
        f.write("];\n")


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>%(title)s &mdash; Map</title>

<!-- Leaflet -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.css" />
<!-- Shared styles -->
<link rel="stylesheet" href="style.css" />
</head>
<body>
  <div class="titlebar" id="titlebar"></div>
  <div id="map"></div>

  <!-- 1) Leaflet  2) this map's data  3) the shared renderer -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.js"></script>
  <script src="%(datafile)s"></script>
  <script src="map.js"></script>
</body>
</html>
"""


def write_html(path, map_title, datafile):
    with open(path, "w", encoding="utf-8") as f:
        f.write(HTML_TEMPLATE % {"title": map_title, "datafile": datafile})


def add_to_index(index_path, html_file, name, note):
    if not os.path.exists(index_path):
        print("(!) %s not found — skipping index update." % index_path)
        return
    with open(index_path, encoding="utf-8") as f:
        text = f.read()
    if ('file: "%s"' % html_file) in text:
        print("index.html already has an entry for %s — leaving it." % html_file)
        return
    marker = "const CHANNELS = ["
    i = text.find(marker)
    if i == -1:
        print("(!) Couldn't find the CHANNELS list in index.html — add the card manually.")
        return
    insert_at = i + len(marker)
    entry = '\n  { file: "%s", name: "%s", note: "%s" },' % (
        html_file, name.replace('"', "'"), (note or "").replace('"', "'"))
    with open(index_path, "w", encoding="utf-8") as f:
        f.write(text[:insert_at] + entry + text[insert_at:])
    print("Added a card to index.html.")


def main():
    ap = argparse.ArgumentParser(description="Build a map page from a curated CSV of places.")
    ap.add_argument("csv", help="CSV file to read (e.g. timeteam-classics.csv)")
    ap.add_argument("--out", default=None, help="Output slug (default: CSV name without .csv)")
    ap.add_argument("--title", default=None, help="Map heading (default: derived from --out)")
    ap.add_argument("--note", default="", help="Description shown on the index.html card")
    ap.add_argument("--no-html", action="store_true", help="Don't (re)write the .html page")
    ap.add_argument("--no-index", action="store_true", help="Don't modify index.html")
    args = ap.parse_args()

    if not os.path.exists(args.csv):
        sys.exit("Couldn't find %s." % args.csv)

    slug = args.out or (args.csv[:-4] if args.csv.lower().endswith(".csv") else args.csv)
    slug = os.path.basename(slug)
    map_title = args.title or slug.replace("-", " ").replace("_", " ").title()

    rows = read_places(args.csv)
    if not rows:
        sys.exit("No rows found in %s." % args.csv)

    js_name = slug + ".js"
    html_name = slug + ".html"
    write_js(os.path.join(ROOT, js_name), map_title, rows)
    print("Wrote %s (%d entries, %d with coordinates)."
          % (js_name, len(rows), sum(1 for r in rows if r["lat"] != "null")))

    if not args.no_html:
        write_html(os.path.join(ROOT, html_name), map_title, js_name)
        print("Wrote %s" % html_name)

    if not args.no_index:
        add_to_index(os.path.join(ROOT, "index.html"), html_name, map_title, args.note)

    print("\nNext: run  python make_previews.py  to refresh the home-page thumbnails.")


if __name__ == "__main__":
    main()
